name: LimbusLive
options:
  bundleIdPrefix: com.northwoodschurch
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "15.0"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Manual

targets:
  LimbusLive:
    type: application
    platform: macOS
    sources:
      - path: LimbusLive
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.northwoodschurch.limbuslive
        PRODUCT_NAME: "Limbus Live"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_LSUIElement: true
        INFOPLIST_KEY_CFBundleDisplayName: "Limbus Live"
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright 2025 Northwoods Community Church"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_USER_SCRIPT_SANDBOXING: false

schemes:
  LimbusLive:
    build:
      targets:
        LimbusLive: all
    run:
      config: Debug
    archive:
      config: Release
