name: LimbusLive
options:
  bundleIdPrefix: com.northwoodschurch
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  defaultConfig: Release

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.0.0

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "15.0"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Manual

targets:
  LimbusLive:
    type: application
    platform: macOS
    sources:
      - path: LimbusLive
    dependencies:
      - package: Sparkle
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.northwoodschurch.limbuslive
        PRODUCT_NAME: "Limbus Live"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_USER_SCRIPT_SANDBOXING: false
    info:
      path: LimbusLive/Info.plist
      properties:
        CFBundleShortVersionString: "1.0.5"
        CFBundleVersion: "1.0.5"
        CFBundleDisplayName: Limbus Live
        LSUIElement: true
        NSHumanReadableCopyright: "Copyright 2025 Northwoods Community Church"
        SUPublicEDKey: VIMxKZmmRokdMcHK5d3QU4+qHgBglmkVFP5aAVvxgqM=
        SUFeedURL: https://northwoodscommunitychurch.github.io/app-updates/appcast-limbuslive.xml

schemes:
  LimbusLive:
    build:
      targets:
        LimbusLive: all
    run:
      config: Debug
    archive:
      config: Release
